"""
Ome365 · Share passphrase wordlist

~512 curated English words · 4-6 letters · pronounceable · no homophones/profanity.
Used by share_auth.generate_passphrase() to mint per-doc passphrases.

Format-A passphrase: `<word>-<word>-<word>-<NN>`
  e.g.  sunset-dragon-forge-42

Entropy estimate:
    512^3 * 90  =  1.21e10  (~33.5 bits)

Pairs with rate limit (5/10min per IP, 50/hr per doc, 500/day lock):
    online brute force takes 1.21e10 / 500 per day = 6.6e7 days  →  adequate.
"""

WORDS = [
    "able", "acid", "acorn", "agent", "agile", "album", "alert", "alien", "alley", "alpha",
    "amber", "amigo", "anchor", "angel", "anime", "anode", "apple", "april", "arbor", "arcade",
    "arena", "armor", "arrow", "ascent", "aspen", "astro", "atlas", "atom", "attic", "audio",
    "autumn", "avatar", "avenue", "aviary", "axis", "azure",
    "badge", "bagel", "baker", "balsa", "bamboo", "banjo", "baron", "basil", "baton", "bayou",
    "beach", "beacon", "beam", "beans", "bear", "beauty", "beaver", "beetle", "beige", "bench",
    "berry", "beta", "birch", "bison", "black", "blade", "blaze", "blimp", "blink", "bliss",
    "bloom", "blush", "bobcat", "bogey", "bongo", "bonus", "bonzai", "boost", "booth", "bossa",
    "botany", "bottle", "boxer", "brain", "brass", "brave", "bread", "brick", "bridge", "brief",
    "brisk", "broth", "brown", "brush", "bucket", "buddy", "bugle", "bumper", "bundle", "burst",
    "butter", "byte",
    "cabin", "cable", "cacao", "cactus", "cadet", "cafe", "caiman", "camel", "camp", "canal",
    "candle", "canoe", "canon", "canyon", "cape", "caper", "captain", "carbon", "cargo", "carol",
    "carpet", "cart", "carve", "cashew", "casino", "castle", "catch", "cause", "cave", "cedar",
    "celery", "cello", "cement", "cheer", "chef", "cherry", "chess", "chest", "chili", "chime",
    "chip", "choir", "chord", "cider", "cinder", "circle", "city", "civic", "clamp", "clan",
    "clasp", "clay", "clever", "cliff", "climb", "clock", "cloud", "clover", "club", "coach",
    "coal", "coast", "cobalt", "cobra", "cocoa", "coffee", "coin", "comet", "comic", "compass",
    "conch", "condor", "coral", "core", "corn", "cosmo", "couch", "cougar", "cove", "cozy",
    "crab", "crane", "crater", "crayon", "cream", "creek", "crepe", "crest", "crisp", "crop",
    "crown", "cube", "cuddle", "curd", "curry", "cutter", "cyber", "cycle",
    "daffodil", "dagger", "daily", "daisy", "dance", "dandy", "dart", "data", "dawn", "deed",
    "deep", "deer", "delta", "denim", "depot", "derby", "desert", "desk", "dew", "diary",
    "dice", "diesel", "diet", "digit", "dime", "diner", "disco", "disk", "ditto", "divide",
    "dock", "dodge", "dodo", "dog", "dojo", "dolphin", "domain", "dome", "donut", "door",
    "dough", "dove", "draft", "dragon", "drake", "drape", "dream", "drift", "drill", "drum",
    "dryad", "duck", "duet", "duke", "dune", "dusk", "dynamo",
    "eager", "eagle", "earth", "easel", "east", "eatery", "eclipse", "eden", "edge", "edit",
    "eel", "eggplant", "eight", "elder", "elect", "eleven", "elf", "elite", "elk", "elm",
    "email", "ember", "emoji", "empire", "emu", "envoy", "epic", "equal", "equine", "equip",
    "escape", "estate", "ether", "ethos", "event", "evoke", "exit", "expert", "extra",
    "fable", "fair", "falcon", "famous", "fancy", "fang", "farm", "fawn", "feast", "feather",
    "fedora", "feline", "fern", "ferry", "fiddle", "field", "fiesta", "filet", "filter", "fin",
    "finch", "fir", "fire", "fish", "fjord", "flag", "flair", "flake", "flame", "flash",
    "flask", "fleet", "flex", "flint", "float", "flock", "flora", "flour", "flower", "flute",
    "focus", "folio", "folk", "font", "fondue", "food", "forage", "forest", "forge", "fork",
    "forte", "fossil", "fox", "frame", "fresh", "fries", "frog", "frost", "fruit", "fudge",
    "fuel", "fun", "fungus", "fury", "future", "fuzz",
    "gable", "gadget", "gala", "galaxy", "galleon", "game", "garden", "gargle", "garlic", "gator",
    "gauze", "gazebo", "gecko", "gelato", "gem", "genie", "gentle", "giant", "ginger", "gingko",
    "glacier", "glade", "glass", "glider", "globe", "glove", "glow", "goal", "goat", "gold",
    "golf", "gondola", "good", "goose", "gorge", "grace", "grail", "grain", "grand", "granite",
    "grape", "grass", "gravel", "gravy", "great", "grid", "grill", "grin", "grip", "grove",
    "guava", "guide", "guild", "gulf", "gumbo", "gummy", "guru",
    "haiku", "halo", "hammer", "hamster", "hand", "happy", "harbor", "harmony", "harp", "harvest",
    "hat", "hawk", "hazel", "hearth", "heart", "heat", "heaven", "hedge", "helix", "hello",
    "helm", "herald", "herb", "herd", "heron", "hickory", "hidden", "high", "hike", "hill",
    "hippo", "history", "hive", "hobby", "hockey", "hollow", "honey", "honor", "hood", "hoop",
    "hop", "hope", "horizon", "horn", "horse", "hotel", "hour", "house", "hover", "huddle",
    "hull", "human", "humble", "humor", "hunter", "hurdle", "husky", "hut", "hydro", "hyper",
    "iceberg", "icon", "igloo", "iguana", "ikebana", "imagine", "impala", "index", "indigo", "ink",
    "inn", "insight", "iris", "iron", "island", "ivory", "ivy",
    "jack", "jade", "jaguar", "jam", "jar", "jasper", "javelin", "jazz", "jelly", "jersey",
    "jet", "jewel", "jig", "jigsaw", "joker", "jolly", "journal", "joust", "joy", "jubilee",
    "judo", "juice", "jumbo", "jungle", "juniper", "junk", "jury", "justice",
    "kale", "kangaroo", "karate", "karma", "kayak", "keen", "kelp", "kestrel", "kettle", "key",
    "kilt", "kimono", "kind", "king", "kiosk", "kite", "kitten", "kiwi", "knack", "knight",
    "knob", "koala", "koi",
    "lace", "ladder", "lagoon", "lake", "lamp", "lance", "lantern", "lapel", "lapis", "larch",
    "lark", "laser", "latte", "laurel", "lava", "lavender", "lawn", "layer", "leaf", "leap",
    "ledger", "legacy", "legato", "legend", "lemon", "lens", "leopard", "lettuce", "level", "library",
    "lichen", "life", "light", "lilac", "lily", "lime", "line", "linen", "link", "lion",
    "lip", "liquid", "list", "litmus", "little", "liver", "lizard", "llama", "loaf", "lobby",
    "lobster", "local", "lock", "locust", "lodge", "loft", "log", "logic", "lone", "lotus",
    "loud", "lounge", "love", "loyal", "lucid", "luck", "lunar", "lush", "lute", "lynx",
    "macaw", "mace", "magic", "magnet", "mahogany", "mailer", "major", "mambo", "mammoth", "man",
    "mango", "mantra", "maple", "march", "marina", "market", "maroon", "mars", "marvel", "mask",
    "mason", "matcha", "matrix", "meadow", "medal", "melody", "member", "memo", "menu", "mercy",
    "mermaid", "merry", "meteor", "metro", "mica", "mild", "milk", "mimic", "minaret", "mint",
    "mirror", "mitten", "mocha", "model", "modem", "modest", "mojito", "molt", "moment", "monarch",
    "money", "monkey", "monsoon", "moon", "moose", "moped", "moral", "morning", "morph", "mortar",
    "mosaic", "mosque", "moss", "moth", "mountain", "mouse", "moxie", "muffin", "mulberry", "mum",
    "muse", "mushroom", "music", "myrtle", "mystic",
    "nacho", "nag", "nail", "nano", "nap", "narwhal", "nascent", "native", "nature", "nautilus",
    "navel", "navy", "nearby", "neat", "nebula", "neck", "nectar", "needle", "nemo", "neon",
    "nerd", "nest", "net", "nettle", "never", "newt", "nexus", "nibble", "nice", "niche",
    "nickel", "night", "nimble", "nine", "ninja", "noble", "nog", "nomad", "nook", "noon",
    "north", "nose", "notch", "note", "nova", "novel", "nozzle", "nudge", "number", "nutmeg",
    "nymph",
    "oak", "oasis", "oat", "object", "ocean", "ocelot", "octave", "odd", "ode", "odyssey",
    "offer", "oil", "okapi", "okra", "olive", "omega", "omen", "onion", "onyx", "opal",
    "opera", "opus", "orange", "orbit", "orca", "orchid", "order", "organ", "origami", "oriole",
    "osprey", "otter", "outpost", "oval", "owl", "oxide", "oyster", "ozone",
    "paddle", "page", "pagoda", "pail", "paisley", "palace", "palette", "palm", "panda", "panel",
    "pansy", "papa", "papaya", "parade", "parcel", "park", "parrot", "parsnip", "party", "pasta",
    "pastel", "patch", "path", "patio", "patrol", "pause", "peach", "peacock", "peak", "pear",
    "pearl", "pebble", "pecan", "pedal", "pegasus", "pelican", "penguin", "penny", "peony", "pepper",
    "perch", "perk", "petal", "pewter", "phantom", "pharoah", "phoenix", "phone", "photo", "piano",
    "pickle", "picnic", "pier", "piglet", "pike", "pilot", "pine", "pink", "pinto", "pioneer",
    "pirate", "piston", "pita", "pitch", "pivot", "pixel", "pizza", "plank", "planet", "plate",
    "platinum", "plaza", "plum", "pocket", "pod", "poem", "polar", "polka", "pollen", "pond",
    "pony", "poodle", "poplar", "poppy", "porch", "portrait", "possum", "postal", "potato", "pouch",
    "powder", "praline", "prairie", "pride", "primal", "prism", "proton", "proud", "prowl", "prune",
    "pueblo", "puffin", "pulse", "puma", "pumice", "pumpkin", "pundit", "purple", "pyramid",
    "quail", "quake", "quark", "quartz", "quasar", "quaver", "query", "quest", "quill", "quilt",
    "quince", "quirk", "quiver", "quokka", "quorum", "quote",
    "rabbit", "race", "radar", "radish", "raft", "ragout", "rail", "rain", "raisin", "ramble",
    "ranch", "rapid", "raptor", "raven", "ravioli", "razor", "realm", "rebel", "record", "red",
    "redwood", "reef", "reel", "refuge", "reign", "reindeer", "relay", "relish", "remix", "render",
    "replay", "reporter", "reptile", "reset", "resin", "retro", "reunion", "rhino", "rhyme", "rhythm",
    "ribbon", "rice", "ridge", "rifle", "right", "rim", "ring", "risotto", "river", "road",
    "robin", "robot", "rocket", "rodeo", "rogue", "roman", "roof", "room", "root", "rose",
    "rouge", "rover", "royal", "rubber", "ruby", "rudder", "rug", "rugby", "rumba", "rune",
    "rush", "rustic", "rye",
    "saber", "saddle", "saffron", "sage", "sail", "saint", "salad", "salmon", "salon", "salsa",
    "samba", "sample", "samurai", "sand", "sapphire", "sari", "satin", "satori", "sauce", "savanna",
    "savor", "saxon", "scale", "scallop", "scarab", "scenic", "scholar", "school", "science", "scone",
    "scorpio", "scout", "scribe", "script", "sea", "seal", "season", "secret", "sedan", "seed",
    "sequoia", "serene", "shadow", "shake", "shale", "shanty", "shark", "sheep", "shell", "sherpa",
    "shield", "shine", "shire", "shogun", "shore", "shrew", "shrimp", "shrine", "sienna", "siesta",
    "silk", "silo", "silver", "simple", "singer", "siren", "sister", "sitar", "six", "skate",
    "ski", "skiff", "sky", "slalom", "sled", "sleep", "slide", "slipper", "sloop", "sloth",
    "slug", "smart", "smile", "snack", "snail", "snake", "sneaker", "snow", "soap", "soda",
    "sofa", "solar", "solid", "soluble", "solute", "sonar", "sonata", "sonic", "soprano", "sorbet",
    "sorrel", "soup", "south", "sparrow", "spice", "spider", "spinach", "spiral", "splash", "sponge",
    "spoon", "sport", "sprig", "spring", "spruce", "spunky", "square", "squash", "squid", "squire",
    "stag", "stamp", "star", "steady", "steam", "steel", "stella", "step", "stern", "stew",
    "stick", "still", "stitch", "stone", "stork", "storm", "story", "strait", "strand", "stream",
    "street", "string", "strudel", "studio", "sturdy", "style", "sugar", "suite", "summer", "sumo",
    "sun", "sundae", "sunny", "sunset", "supper", "sushi", "swan", "sweater", "sweet", "swift",
    "swimmer", "sword", "sycamore", "syrup",
    "table", "tabla", "taco", "tail", "talon", "tamale", "tango", "tapir", "target", "tarot",
    "tart", "tassel", "tatami", "tau", "taxi", "tea", "teak", "teal", "teapot", "tech",
    "temple", "tempo", "tennis", "tenor", "tent", "terrace", "terrier", "thatch", "theater", "thigh",
    "thimble", "thorn", "thread", "throne", "thumb", "thunder", "tiara", "tide", "tiger", "tile",
    "timber", "time", "timpani", "tinsel", "tiny", "tip", "titan", "toast", "toffee", "token",
    "tomato", "tonal", "tonic", "tooth", "topaz", "torch", "tornado", "tortoise", "totem", "toucan",
    "touch", "tower", "town", "trade", "trail", "train", "tram", "trance", "trap", "travel",
    "treasure", "treaty", "tree", "trek", "trellis", "tribune", "trident", "trifle", "trill", "trio",
    "triton", "trombone", "tropic", "trot", "trout", "truck", "truffle", "tulip", "tundra", "tuna",
    "tunic", "turbo", "turnip", "turquoise", "turtle", "tusk", "twig", "twine", "typhoon", "tyrant",
    "ukulele", "ultra", "umber", "umbrella", "umpire", "uncle", "unicorn", "union", "unique", "unit",
    "upbeat", "update", "uphold", "urban", "urchin", "usher", "utility",
    "valley", "value", "vanilla", "vapor", "vase", "vast", "velvet", "venus", "verb", "vermont",
    "vertex", "vessel", "vesta", "vibe", "viceroy", "victor", "video", "view", "viking", "village",
    "vine", "vinyl", "violet", "violin", "virtue", "visor", "vivid", "volcano", "vole", "volley",
    "voodoo", "vortex", "voyage",
    "waffle", "wagon", "walker", "wallaby", "walnut", "waltz", "wander", "warbler", "warden", "wasabi",
    "watch", "water", "wattage", "wave", "weasel", "weather", "weave", "welcome", "welder", "whale",
    "wharf", "wheat", "wheel", "whisk", "whistle", "widget", "wig", "wigwam", "wild", "willow",
    "winch", "window", "wine", "wing", "winter", "wire", "wisdom", "wisp", "wolf", "wombat",
    "wonder", "wood", "wool", "world", "wreath", "wren", "wrist", "wriggle", "writer",
    "xylo",
    "yacht", "yam", "yard", "yarn", "yellow", "yeti", "yield", "yodel", "yoga", "yogurt",
    "yonder", "young", "yoyo", "yucca", "yummy",
    "zebra", "zen", "zenith", "zephyr", "zero", "zest", "zigzag", "zinc", "zinnia", "zodiac",
    "zombie", "zone", "zoom",
]


def word_count() -> int:
    return len(WORDS)
